apiVersion: v1
kind: Namespace
metadata:
  name: voting-app
  labels:
    name: voting-app
    environment: development
    # PSA Labels - مضافة
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
