apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-isolation
  namespace: voting-app
spec:
  podSelector:
    matchLabels:
      app: db  # ← تطبق على PostgreSQL فقط
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: worker   # ← يسمح للـ Worker فقط
    - podSelector:
        matchLabels:
          app: result   # ← يسمح للـ Result فقط
    ports:
    - protocol: TCP
      port: 5432        # ← البورت الخاص بـ PostgreSQL فقط
