apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: voting-app
type: Opaque
data:
  username: cG9zdGdyZXM=    # ← postgres encoded
  password: cG9zdGdyZXM=    # ← postgres encoded
