apiVersion: apps/v1
kind: Deployment
metadata:
  name: seed
  labels:
    app: seed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seed
  template:
    metadata:
      labels:
        app: seed
    spec:
      containers:
        - name: seed
          image: seed_image:latest
       

